apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ciapi-provisioning-service
  creationTimestamp: null
  labels:
    app: ciapi-provisioning-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ciapi-provisioning-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ciapi-provisioning-service
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/ciapi-provisioning-service:NR-202201200639-553d812
          name: ciapi-provisioning-service
          imagePullPolicy: Always
          env:
              - name: JAVA_TOOL_OPTIONS
                value: "-Dserver.port=80 -Dspring.application.name=ciapi-provisioning-service"
              - name: SPRING_PROFILES_ACTIVE
                value: "_APP_PROFILE"
              - name: SPRING_APPLICATION_NAME
                value: "ciapi-provisioning-service"
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /var/secrets/google/gkey.json
          livenessProbe:
            httpGet:
              path: /message
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: ciapi-provisioning-service
              mountPath: /config
            - name: pub-sub-v
              mountPath: /var/secrets/google
      volumes:
        - name: ciapi-provisioning-service
          configMap:
            name: ciapi-provisioning-service-qa
        - name: pub-sub-v
          secret:
            secretName: iid-pub-sa-key
status: {}
