apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: ci-search-social-site-service
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 15
    port: 80
    type: HTTP
    requestPath: /message