apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ci-search-social-site-service
  creationTimestamp: null
  labels:
    app: ci-search-social-site-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ci-search-social-site-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ci-search-social-site-service
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/ci-search-social-site-service:latest
          name: ci-search-social-site-service
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dserver.port=80 -Dspring.application.name=ci-search-social-site-service"
            - name: SPRING_PROFILES_ACTIVE
              value: "_APP_PROFILE"
            - name: SPRING_APPLICATION_NAME
              value: "ci-search-social-site-service"
          livenessProbe:
            httpGet:
              path: /message
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: ci-search-social-site-service
              mountPath: /config
      volumes:
        - name: ci-search-social-site-service
          configMap:
            name: ci-search-service-qa
status: {}

