apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ciapi-user-subscription-service
  creationTimestamp: null
  labels:
    app: ciapi-user-subscription-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ciapi-user-subscription-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ciapi-user-subscription-service
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/ciapi-user-subscription-service:NR-202201200710-93a129a
          name: ciapi-user-subscription-service
          imagePullPolicy: Always
          env:
              - name: JAVA_TOOL_OPTIONS
                value: "-Dserver.port=80 -Dspring.application.name=ciapi-user-subscription-service"
              - name: SPRING_PROFILES_ACTIVE
                value: "${ENVIRONMENT}"
              - name: ENVIRONMENT
                valueFrom:
                  configMapKeyRef:
                    name: profile-config
                    key: ENVIRONMENT
              - name: SPRING_APPLICATION_NAME
                value: "ciapi-user-subscription-service"
          livenessProbe:
            httpGet:
              path: /message
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: ciapi-user-subscription-service
              mountPath: /config
      volumes:
        - name: ciapi-user-subscription-service
          configMap:
            name: ciapi-user-subscription-service-qa

status: {}