apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: iid-qa
  name: ciapi-mass-processing
  creationTimestamp: null
  labels:
    app: ciapi-mass-processing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciapi-mass-processing
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ciapi-mass-processing
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/ciapi-mass-processing:latest
          imagePullPolicy: Always
          name: ciapi-mass-processing
          env:
              - name: JAVA_TOOL_OPTIONS
                value: "-Dserver.port=80 -Dspring.application.name=ciapi-mass-processing -Dnewrelic.config.log_file_name=STDOUT -Dnewrelic.config.license_key=d67210cdd7109fefbfdf3b9739f77e7d53acee76 -Dnewrelic.config.app_name=gcp-ciapi-mass-processing -Dnewrelic.config.orgs=CommonIdentity -Dnewrelic.enable.java.8=true -javaagent:/newrelic/newrelic.jar -Dnewrelic.home=/newrelic -Dnewrelic.environment=test"
              - name: SPRING_PROFILES_ACTIVE
                value: "qa,swn01-qa,gcp"
              - name: SPRING_APPLICATION_NAME
                value: "ciapi-mass-processing"
          livenessProbe:
            httpGet:
              path: /message
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: ciapi-mass-processing
              mountPath: /config
      volumes:
        - name: ciapi-mass-processing
          configMap:
            name: ciapi-mass-processing-qa
status: {}
