#Reference
#west Cluster
#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'push-filebeat'
#  args: ['apply', '-f', 'filebeat']
#  env:
#    - 'CLOUDSDK_CORE_PROJECT=cc-bo-portals-devtest-02'
#    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=stg-us-central1-cluster-1'
#  waitFor:
#    - '-'

#- name: 'gcr.io/cloud-builders/gcloud'
#  entrypoint: 'bash'
#  args:
#    - '-c'
#    - |
#      gcloud container clusters get-credentials stg-us-central1-cluster-1 --zone us-central1-a --project cc-bo-portals-devtest-02
#      rm -rf ~/.kube/config
#      gcloud config get-value project
#      gcloud container clusters list
#      gcloud components install kubectl
#      apt-get install kubectl
#      gcloud config set project cc-bo-portals-devtest-02
#      gcloud container clusters get-credentials stg-us-central1-cluster-1 --zone us-central1-a --project cc-bo-portals-devtest-02
#      gcloud config get-value project
#      gcloud config set project cc-bo-portals-devtest-02
#      kubectl --insecure-skip-tls-verify=true get nodes
#      gcloud config set project cc-bo-portals-devtest-02
#      kubectl --insecure-skip-tls-verify=true get all
#      gcloud container clusters list
#      cat ~/.kube/config
#  env:
#    - 'CLOUDSDK_CORE_PROJECT=cc-bo-portals-devtest-02'
#    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=stg-us-central1-cluster-1'

#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'push-filebeat-west'
#  args: ['apply', '-f', 'filebeat']
#  env:
#    - 'CLOUDSDK_CORE_PROJECT=cc-bo-portals-devtest-01'
#    - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=us-west1-cluster-1'
#  waitFor:
#    - '-'
#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'push-filebeat-central'
#  args: ['apply', '-f', 'filebeat']
#  env:
#    - 'CLOUDSDK_CORE_PROJECT=cc-bo-portals-devtest-01'
#    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=us-central1-cluster-1'
#  waitFor:
#    - 'push-filebeat-west'

#- name: 'ubuntu'
#  id: 'prepare-build'
#  args: ['bash', './prepare-build.sh']
#  waitFor:
#    - '-'

#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'testing'
#  #args: ['delete', '-f', 'push-name-space']
#  args: ['get', 'nodes']
#  env:
#    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
#    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'

#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'create-name-space'
#  #args: ['delete', '-f', 'push-name-space']
#  args: ['get', 'nodes']
#  env:
#    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
#    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
#  waitFor: ['prepare-build']
#
#  - name: 'gcr.io/cloud-builders/kubectl'
#    id: 'push-filebeat-central'
#    args: ['apply', '-f', 'stage-apis']
#    env:
#      - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
#      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
#      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
#    waitFor: ['prepare-build']

steps:
- name: 'gcr.io/cloud-builders/kubectl'
  id: 'install-certs'
  args: ['delete', '-f', 'managed-certificates']
  env:
    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  waitFor: ['-']

- name: 'ubuntu'
  id: 'prepare-build'
  args: ['bash', './prepare-build.sh']
  env:
    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
    - '_APPLICTION_PROFILE=${_APPLICTION_PROFILE}'
  waitFor:
    - '-'

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'push-filebeat-central'
  args: ['delete', '-f', 'filebeat']
  env:
    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  waitFor: ['-']



- name: 'gcr.io/cloud-builders/kubectl'
  id: 'push-configs'
  args: ['apply', '-f', 'config']
  env:
    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'dps-alert-monitor'
  args: ['delete', '-f', 'dps-alert-monitor']
  env:
    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/gcloud'
  id: 'pub-sub-key'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      export PROJECT_ID=$_CLOUDSDK_CORE_PROJECT

      gcloud container clusters get-credentials $_CLOUDSDK_CONTAINER_CLUSTER --region $_CLOUDSDK_COMPUTE_ZONE --project $_CLOUDSDK_CORE_PROJECT

      #Clean
      #kubectl delete secret iid-pub-sa-key
      #gcloud projects remove-iam-policy-binding $PROJECT_ID --role "roles/pubsub.editor"  --member "serviceAccount:iid-pub-sa@$PROJECT_ID.iam.gserviceaccount.com"
      #gcloud iam service-accounts delete -q  iid-pub-sa@$PROJECT_ID.iam.gserviceaccount.com

      gcloud iam service-accounts create iid-pub-sa --display-name "service account for publishing/subscribing messages"
      gcloud projects add-iam-policy-binding $PROJECT_ID --role "roles/pubsub.editor"  --member "serviceAccount:iid-pub-sa@$PROJECT_ID.iam.gserviceaccount.com"
      gcloud iam service-accounts keys create ./pubkey.json --iam-account iid-pub-sa@$PROJECT_ID.iam.gserviceaccount.com
      #gcloud auth activate-service-account --project=$PROJECT_ID --key-file=./pubkey.json
      kubectl create secret generic iid-pub-sa-key --from-file=gkey.json=./pubkey.json  || exit 0
  env:
    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  waitFor: ['prepare-build']

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'push-apis'
  args: ['delete', '-f', 'stage-apis']
  env:
    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  waitFor: ['pub-sub-key','push-configs','prepare-build']

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'push-portals'
  args: ['delete', '-f', 'stage-portals']
  env:
    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  waitFor: ['prepare-build','pub-sub-key','push-configs','push-apis']

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'push-ingress'
  args: ['delete', '-f', '${_CLOUDSDK_CONTAINER_INGRESS}']
  env:
    - 'CLOUDSDK_CORE_PROJECT=${_CLOUDSDK_CORE_PROJECT}'
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
  waitFor: ['install-certs','prepare-build','pub-sub-key','push-configs','push-apis','push-portals']

timeout: 600s
options:
  workerPool: 'projects/cc-bo-portals-devtest-01/locations/us-central1/workerPools/cloud-build-private-pool'
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _CLOUDSDK_CORE_PROJECT: 'cc-bo-portals-devtest-01'
  _CLOUDSDK_COMPUTE_ZONE: 'us-central1'
  _CLOUDSDK_CONTAINER_CLUSTER: 'us-central1-cluster-1'
  _CLOUDSDK_CONTAINER_INGRESS: 'ingress-central'
  _APPLICTION_PROFILE: 'qa,swn01-qa'

#West

  #_CLOUDSDK_CORE_PROJECT: 'cc-bo-portals-devtest-01'
  #_CLOUDSDK_COMPUTE_ZONE: 'us-west1'
  #_CLOUDSDK_CONTAINER_CLUSTER: 'us-west1-cluster-1'
  #_CLOUDSDK_CONTAINER_INGRESS: 'ingress-west'
  #_APPLICTION_PROFILE: 'qa,den06-qa'
