steps:
- name: 'gcr.io/cloud-builders/kubectl'
  #args: ['apply', '-f', 'cif-launchpad']
  args: ['get', 'nodes']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cc-bo-portals-devtest-01-west-gke'
timeout: 1200s
options:
  pool:
    name: 'projects/cc-bo-portals-devtest-01/locations/us-west1/workerPools/iid'