steps:
#west Cluster
- name: 'ubuntu'
  id: 'prepare-build'
  args: ['bash', './prepare-build.sh']
  waitFor:
    - '-'

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'push-configs'
  args: ['apply', '-f', 'config']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=us-west1-cluster-1'
  waitFor:
    - '-'

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'push-apis'
  args: ['apply', '-f', 'stage-apis']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=us-west1-cluster-1'
  waitFor:
    - 'prepare-build'
    - 'push-configs'

- name: 'gcr.io/cloud-builders/kubectl'
  id: 'push-portals'
  args: ['apply', '-f', 'stage-portals']
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=us-west1-cluster-1'
  waitFor:
    - 'prepare-build'
    - 'push-configs'
    - 'push-apis'

timeout: 600s
options:
  workerPool: 'projects/cc-bo-portals-devtest-01/locations/us-central1/workerPools/cloud-build-private-pool'
  logging: CLOUD_LOGGING_ONLY