steps:
#west Cluster
#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'push-filebeat'
#  args: ['apply', '-f', 'filebeat','--insecure-skip-tls-verify=true']
#  env:
#    - 'CLOUDSDK_CORE_PROJECT=cc-bo-portals-prod-01'
#    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=us-central1-cluster-1'
#  waitFor:
#    - '-'

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud container clusters get-credentials us-central1-cluster-1 --region us-central1 --project cc-bo-portals-prod-01
      gcloud components install kubectl
      kubectl get nodes
  env:
    - 'CLOUDSDK_CORE_PROJECT=cc-bo-portals-prod-01'
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
    - 'CLOUDSDK_CONTAINER_CLUSTER=us-central1-cluster-1'
#- name: 'ubuntu'
#  id: 'prepare-build'
#  args: ['bash', './prepare-build.sh']
#  waitFor:
#    - '-'
#
#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'push-configs'
#  args: ['apply', '-f', 'config']
#  env:
#    - 'CLOUDSDK_CORE_PROJECT=cc-bo-portals-devtest-01'
#    - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=us-west1-cluster-1'
#  waitFor:
#    - '-'
#
#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'push-apis'
#  args: ['apply', '-f', 'stage-apis']
#  env:
#  - 'CLOUDSDK_CORE_PROJECT=cc-bo-portals-devtest-01'
#  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=us-west1-cluster-1'
#  waitFor:
#    - 'prepare-build'
#    - 'push-configs'
#
#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'push-portals'
#  args: ['apply', '-f', 'stage-portals']
#  env:
#    - 'CLOUDSDK_CORE_PROJECT=cc-bo-portals-devtest-01'
#    - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=us-west1-cluster-1'
#  waitFor:
#    - 'prepare-build'
#    - 'push-configs'
#    - 'push-apis'
#
#- name: 'gcr.io/cloud-builders/kubectl'
#  id: 'push-ingress-west'
#  args: ['apply', '-f', 'ingress-west']
#  env:
#    - 'CLOUDSDK_CORE_PROJECT=cc-bo-portals-devtest-01'
#    - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
#    - 'CLOUDSDK_CONTAINER_CLUSTER=us-west1-cluster-1'
#  waitFor:
#    - 'prepare-build'
#    - 'push-configs'
#    - 'push-apis'
#    - 'push-portals'

timeout: 600s
options:
  workerPool: 'projects/cc-bo-portals-devtest-01/locations/us-central1/workerPools/cloud-build-private-pool'
  logging: CLOUD_LOGGING_ONLY