steps:
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'cif-launchpad']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cc-bo-portals-devtest-01-west-gke'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'westid-rna']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cc-bo-portals-devtest-01-west-gke'

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'filebeat']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=cc-bo-portals-devtest-01-west-gke'
options:
  pool:
    name: 'projects/cc-bo-portals-devtest-01/locations/us-central1/workerPools/iid'