steps:

#- name: 'gcr.io/cloud-builders/kubectl'
#  args: ['apply', '-f', 'cif-launchpad']
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=cc-bo-portals-devtest-01-gke'
#
#- name: 'gcr.io/cloud-builders/kubectl'
#  args: ['apply', '-f', 'westid-rna']
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=cc-bo-portals-devtest-01-gke'
#
#- name: 'gcr.io/cloud-builders/kubectl'
#  args: ['apply', '-f', 'filebeat']
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=cc-bo-portals-devtest-01-gke'
#
#- name: 'gcr.io/cloud-builders/kubectl'
#  args: ['apply', '-f', 'ciapi-business-service']
#  env:
#  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
#  - 'CLOUDSDK_CONTAINER_CLUSTER=cc-bo-portals-devtest-01-gke'

#west
- name: 'ubuntu'
  id: 'prepare-build'
  args: ['bash', './prepare-build.sh']
  #entrypoint: 'bash'
  #args:
  #  - '-c'
  #  - |
  #    echo "***** current directory *** $(ls $PWD)"
  #    ./prepare-build.sh
  #    echo $(ls)
  #    echo "***** staging directory for deployment *** $(ls $PWD/out)"

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', 'out']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-west1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=us-west1-cluster-1'
  waitFor:
    - 'prepare-build'
timeout: 400s
options:
  workerPool: 'projects/cc-bo-portals-devtest-01/locations/us-central1/workerPools/cloud-build-private-pool'
  logging: CLOUD_LOGGING_ONLY