apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ci-search-email-service
  creationTimestamp: null
  labels:
    app: ci-search-email-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "ci-search-email-service"}'
spec:
  ports:
  - name: ci-search-email-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ci-search-email-service
  type: ClusterIP