apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cif-admin-portal
  creationTimestamp: null
  labels:
    app: cif-admin-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cif-admin-portal
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: cif-admin-portal
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/cif-admin-portal:FB-devops-451-202201110614-e51638d
          name: cif-admin-portal
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dserver.port=80 -Dspring.application.name=cif-admin-portal"
            - name: SPRING_PROFILES_ACTIVE
              value: "_APP_PROFILE"
            - name: SPRING_APPLICATION_NAME
              value: "cif-admin-portal"
          livenessProbe:
            httpGet:
              path: /message
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: cif-admin-portal
              mountPath: /config
      volumes:
        - name: cif-admin-portal
          configMap:
            name: ci-portal-service-qa
status: {}