apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: cif-admin-portal-service
  labels:
    app: cif-admin-portal
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"ap-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
    #kubernetes.io/ingress.global-static-ip-name: "cif-admin-portal-ingress-ip"
spec:
  type: LoadBalancer
  #loadBalancerIP: 34.132.65.238
  #loadBalancerIP: 10.113.100.24
  #loadBalancerIP: 34.149.24.25
  #loadBalancerIP: 104.198.53.33
#  externalTrafficPolicy: Local 34.134.221.90
  selector:
    app: cif-admin-portal
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80