apiVersion: v1
kind: Service
metadata:
  namespace: ${name_space}
  name: cif-admin-portal-service
  labels:
    app: cif-admin-portal
  annotations:
    cloud.google.com/backend-config: '{"ports": {"80":"ap-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
    kubernetes.io/ingress.global-static-ip-name: "cif-admin-portal-ingress-ip"
spec:
  type: LoadBalancer
#  externalTrafficPolicy: Local
  selector:
    app: cif-admin-portal
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80