apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: lp-backendconfig
spec:
  timeoutSec: 300
  connectionDraining:
    drainingTimeoutSec: 1800
  sessionAffinity:
    affinityType: "GENERATED_COOKIE"
    affinityCookieTtlSec: 1800
  healthCheck:
    checkIntervalSec: 300
    timeoutSec: 300
    type: HTTP
    requestPath: /endpoints/health
    port: 80