apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: cif-launchpad
  labels:
    app: cif-launchpad
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cif-launchpad
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  template:
    metadata:
      labels:
        app: cif-launchpad
    spec:
      containers:
        - name: cif-launchpad
          image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/cif-launchpad:NR-202201190522-a754d30
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dserver.port=80 -Dspring.application.name=cif-launchpad"
            - name: SPRING_PROFILES_ACTIVE
              value: "${ENVIRONMENT}"
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: profile-config
                  key: ENVIRONMENT
            - name: SPRING_APPLICATION_NAME
              value: "cif-launchpad"
#            - name: HOSTNAME
#              valueFrom:
#                fieldRef:
#                  fieldPath: metadata.name
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /endpoints/health
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: cif-launchpad
              mountPath: /config
      volumes:
        - name: cif-launchpad
          configMap:
            name: cif-launchpad-qa