apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ciapi-wso2is-authentication-log-service
  creationTimestamp: null
  labels:
    app: ciapi-wso2is-authentication-log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciapi-wso2is-authentication-log-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ciapi-wso2is-authentication-log-service
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/ciapi-wso2is-authentication-log-service:NR-202201200727-8fbefff
          imagePullPolicy: Always
          name: ciapi-wso2is-authentication-log-service
          env:
              - name: JAVA_TOOL_OPTIONS
                value: "-Dserver.port=80 -Dspring.application.name=ciapi-wso2is-authentication-log-service"
              - name: SPRING_PROFILES_ACTIVE
                value: "${ENVIRONMENT}"
              - name: ENVIRONMENT
                valueFrom:
                  configMapKeyRef:
                    name: profile-config
                    key: ENVIRONMENT
              - name: SPRING_APPLICATION_NAME
                value: "ciapi-wso2is-authentication-log-service"
          livenessProbe:
            httpGet:
              path: /message
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: ciapi-wso2is-authentication-log-service
              mountPath: /config
      volumes:
        - name: ciapi-wso2is-authentication-log-service
          configMap:
            name: ciapi-wso2is-authentication-log-service-qa
status: {}
