apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ciapi-application-service
  creationTimestamp: null
  labels:
    app: ciapi-application-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ciapi-application-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ciapi-application-service
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/ciapi-application-service:latest
          name: ciapi-application-service
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dserver.port=80 -Dspring.application.name=ciapi-application-service"
            - name: SPRING_PROFILES_ACTIVE
              value: "${ENVIRONMENT}"
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: profile-config
                  key: ENVIRONMENT
            - name: SPRING_APPLICATION_NAME
              value: "ciapi-application-service"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/gkey.json
          livenessProbe:
            httpGet:
              path: /message
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: ciapi-application-service
              mountPath: /config
            - name: pub-sub-v
              mountPath: /var/secrets/google
      volumes:
        - name: ciapi-application-service
          configMap:
            name: ciapi-application-service-qa
        - name: pub-sub-v
          secret:
            secretName: iid-pub-sa-key
status: {}
