apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  name: ci-catalog-service
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 16
    port: 80
    type: HTTP
    requestPath: /message