apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: dps-alert-monitor-ui
  labels:
    app: dps-alert-monitor-ui
spec:
  selector:
    matchLabels:
      app: dps-alert-monitor-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: dps-alert-monitor-ui
    spec:
      containers:
        - name: dps-alert-monitor-ui
          image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/dps/dps-alert-monitor-ui:FB-DPSC-2689-202202280904-c4bd655
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dserver.port=80 -Dspring.application.name=dps-alert-monitor-ui"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/gkey.json
            - name: SPRING_PROFILES_ACTIVE
              #value: "qa"
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: dps-alert-monitor-ui-config-aljg
            - name: PCC_API_URL
              #value: "https://dps-alert-pcc-api-i5yvaantoq-uc.a.run.app/"
              valueFrom:
                configMapKeyRef:
                  key: PCC_API_URL
                  name: dps-alert-monitor-ui-config-aljg
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              port: 80
              path: /endpoints/health
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: run-invoker-v
              mountPath: /var/secrets/google
      volumes:
        - name: run-invoker-v
          secret:
            secretName: iid-pub-sa-key
