apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  creationTimestamp: null
  name: ci-portal-service-qa
  #resourceVersion: "1.0"
  #uid: f6fbeddf-7555-49d9-ad83-204516ca2c75
data:
  application-qa.yml: |
    ---
    health.config.enabled: false
    spring:
      database: POSTGRESQL
      show-sql: true
      datasource:
        platform: postgres
        driverClassName: org.postgresql.Driver
        factory: org.apache.tomcat.jdbc.pool.DataSourceFactory
        pool-size: 60
        tomcat:
          max-age: 1800000
          max-wait: 10000
          max-active: 60
          initial-size: 12
          max-idle: 6
          min-idle: 6
          time-between-eviction-runs-millis: 30000
          min-evictable-idle-time-millis: 30000
          remove-abandoned: true
          remove-abandoned-timeout: 120
          log-abandoned: true
          abandon-when-percentage-full: 0
          test-on-borrow: true
          validation-query: select 1
          validation-interval: 20000
          test-while-idle: true
          test-on-connect: true
          log-validation-errors: true
          jdbcInterceptors: ConnectionState;StatementFinalizer;QueryTimeoutInterceptor(queryTimeout=90);SlowQueryReport(threshold=30000);ResetAbandonedTimer
        username: ciportal
        password: ciportal
      aop:
        proxy-target-class: true
    logging:
      pattern:
        console: |
          %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{APP_NAME:-${newrelic.config.process_host.display_name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-},%X{SPACE_NAME:-${cloud.application.space_name:-}},%X{authuser},%X{_tid_}] 00 --- [%t] %logger : %replace(%msg){'[\r\n]',' -- '}--%replace(%ex){'[\r\n]',' -- '}%n
        level: |
          %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{APP_NAME:-${newrelic.config.process_host.display_name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-},%X{SPACE_NAME:-${cloud.application.space_name:-}},%X{authuser},%X{_tid_}] 00 --- [%t] %logger : %replace(%msg){'[\r\n]',' -- '}--%replace(%ex){'[\r\n]',' -- '}%n
      level:
        com.west: INFO
        com.west.ci.filter: DEBUG
        com.westuc: ERROR
        com.netflix: WARN
        org.apache: WARN
        org.spring: WARN
        org.springframework: WARN
        org.hibernate: WARN
        org.newrelic: WARN
        org.springframework.aop.interceptor.CustomizableTraceInterceptor: ERROR
        com.newrelic: INFO
    server.error.include-message: always
    server.servlet.encoding.force: true
    eureka.client.enabled: false
    management.health.rabbit.enabled: false
    message: '****|${spring.application.name}|****'
    search:
      result:
        maxResults: 50000
    resource-service.request.timeout: 400000
    resource-service.read.timeout: 400000

    url:
      hootRender: https://admin:Testing1@whatsnew.qa.hootmeeting.com/apView.htm
      umxRender: https://admin:Testing1@whatsnew.qa.umx.conferencing.com/apView.htm
      gateway: http://
      host: https://ci-portal.app.pcftest.one.west.com
      apigee:
        log-service: https://ci-log-service.app.pcftest.one.west.com/
        apiKey: gj5UyZeeydxKWIgWdotWFZ9urjlfN1sc
        env: omaha
        searchEndPoints:
          application: ci-search-application-service:80
          attribute: ci-search-attribute-service:80
          business: ci-search-business-service:80
          customer: ci-search-customer-service:80
          email: ci-search-email-service:80
          social-site: ci-search-social-site-service:80
          template: ci-search-template-service:80
          user: ci-search-user-service:80
          release: ci-search-release-service:80
        servicesEndPoints:
          catalog: ci-catalog-service:80
          application: ciapi-application-service:80/applications
          business: ciapi-business-service:80/business
          customer: ciapi-customer-service:80/customers
          customerSubscription: ciapi-customer-subscription-service:80/customers
          user: ciapi-user-service:80/users
          userSubscription: ciapi-user-subscription-service:80/users
          provisioning: ciapi-provisioning-service:80/provisioning
          release: ciapi-release-notes-service:80

    nr.insights.enabled: true
    nr.insights.date.format: MM/dd/yyyy hh:mm aa z

    server:
      compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
      session:
        timeout: 14400
    security:
      user:
        password: none
      oauth2:
        client:
          clientId: 8roQGQqcxfGnNFZAzXn3GzysaVQa
          clientSecret: KsVLAX4zAY8I2hsYb9x6oPtePdAa
          accessTokenUri: https://cidm-qa.uccenter.com/oauth2/token
          userAuthorizationUri: https://cidm-qa.uccenter.com/oauth2/authorize
          redirectUri: https://ci-portal.app.pcftest.one.west.com/login
          clientAuthenticationScheme: form
          grant-type: authorization_code
          authorized-grant-types: code
        resource:
          jwt:
            keyValue: -----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEArt/0PHxQpuhjVmQWwE4ruKUdtGqaKj2xoipo2VK55uWvm/O/gCq5+yEz8mlKLGihX/L7+0D9iijpVUWK37UgY6hR3FP6HTEDPlm1kZAn5FEdosca7ATR0vmqe1DuZThbsRWhE0iDUPbF3spgqflYzgR7+lnuS/6uQw5F8lnvlIVhy9GOQmyJS62dzgARpkQmdc7p9Qfb17Xcu4WAO6VhzrmCBCuclLHLlw3ZI+E/SS4V9gMyW+lIcA+zqNKmAjNm/eEcDPrD46WgEZuuKRNysLi2GQ+wYuRkrAe8J9wNTDIoB6RB8WLLJ9fq8eE1GMCdocTr0PPGBUuG+iMxkuFS0QIDAQAB-----END PUBLIC KEY-----

    #config and rabbit MQ bindings & zipkin
#    ---
#    spring:
#      profiles: swn01-qa
#      datasource:
#        url: 'jdbc:postgresql://cidmdb-rw-qa-swn01.west.com:5432/cidmdb?currentSchema=ciapi_qa'
#
#    ---
#    spring:
#      profiles: den06-qa
#      datasource:
#        url: 'jdbc:postgresql://cidmdb-rw-qa-den06.west.com:5432/cidmdb?currentSchema=ciapi_qa'
  application-den06-qa.yml: |
    spring:
      datasource:
        url: 'jdbc:postgresql://cidmdb-rw-qa-den06.west.com:5432/cidmdb?currentSchema=ciapi_qa'
  application-swn01-qa.yml: |
    spring:
      datasource:
        url: 'jdbc:postgresql://cidmdb-rw-qa-swn01.west.com:5432/cidmdb?currentSchema=ciapi_qa'