apiVersion: v1
kind: ConfigMap
metadata:
  namespace: iid-qa
  creationTimestamp: null
  name: ciapi-business-service-qa
  #resourceVersion: "1.0"
  #uid: 36735833-5435-4380-b7fd-3685d613f6ad
data:
  application-qa.yml: |
    ---
    spring:
      config:
        activate:
          on-profile: qa
      datasource:
        username: itcbapi
        password: itcbapiq
        driverClassName: org.postgresql.Driver
        factory: org.apache.tomcat.jdbc.pool.DataSourceFactory
        tomcat:
          max-age: 1800000
          max-wait: 30000
          max-active: 4
          initial-size: 1
          max-idle: 1
          min-idle: 1
          time-between-eviction-runs-millis: 30000
          min-evictable-idle-time-millis: 30000
          remove-abandoned: true
          remove-abandoned-timeout: 600
          log-abandoned: true
          abandon-when-percentage-full: 0
          test-on-borrow: true
          validation-query: select 1
          validation-interval: 20000
          test-while-idle: true
          test-on-connect: true
          log-validation-errors: true
          jdbcInterceptors: ConnectionState;StatementFinalizer;QueryTimeoutInterceptor(queryTimeout=90);SlowQueryReport(threshold=30000);ResetAbandonedTimer
      messages:
        basename: common-messages,messages
        cache-duration: -1
        encoding: UTF-8
      aop:
        proxy-target-class: true
      mvc:
        async:
          request-timeout: 90000
      cloud:
        gcp:
          config:
            project-id: cc-bo-portals-devtest-01
        services:
          registrationMethod: route
        stream:
          overrideCloudConnectors: false
          bindings:
            output:
              destination: ciapi-internal-email
              content-type: application/json
              producer:
                requiredGroups: email
          #binders:
          #  rabbit-ciapi:
          #    type: rabbit
          #    environment:
          #      spring:
          #        rabbitmq:
          #          cache:
          #            channel:
          #              checkout-timeout: 90000
          #              size: 10
          #          connection-timeout: 0
          #          requested-heartbeat: 30
      security:
        user:
          name: ciusapi
          password: x3iY9P&*8%zK
          roles: CIAPIUSER,APP_CLIENT,ISUSER
    twilio:
      service:
        enabled: false
      api:
        accountSid: AC3e89160e70a9d54f630b138fc0534a17
        authToken: 4c976a058361049484840a203fd8f775
        serviceId: VA5f2d01c87c30d30956fcf59b96514b78
    management:
      endpoints:
        enabled-by-default: false
        web:
          exposure:
            include: '*'
          base-path: /management/ciapi/business/
      endpoint:
        info:
          enabled: true
        health:
          enabled: true
          show-details: always
        metrics:
          enabled: true
        env:
          enabled: true
    endpoints:
      health:
        sensitive: false
    #eureka:
    #  instance:
    #    hostname: ${app_registry_uri}
    #    instanceId: ${app_registry_uri}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    #    status-page-url-path: /management/ciapi/business/info
    #    health-check-url-path: /management/ciapi/business/health
    #  client:
    #    healthcheck:
    #      enabled: true
    #    heartbeat-executor-thread-pool-size: 20
    #    cache-refresh-executor-thread-pool-size: 20
    #    eureka-server-total-connections-per-host: 100
    #    eureka-server-connect-timeout-seconds: 15
    #    eureka-server-read-timeout-seconds: 20
    ciapi:
      database:
        schema: ciapi_qa
      security:
        oauth2:
          uri:
            antpattern: /business/**
        basic:
          uri:
            antpattern: /business/**
          roles: CIAPIUSER,APP_CLIENT,ISUSER
          users:
            -
              username: ciusapi
              password: x3iY9P&*8%zK
              roles: CIAPIUSER,APP_CLIENT
      jwt:
        key:
          file: wso2carbon-test.cert
    httpclient:
      max-total-connections: 1000
      max-route-connections: 200
      default-keep-alive-time: 30000
      idle-connection-wait-time: 30000
      connect-timeout: 20000
      request-timeout: 60000
      socket-timeout: 60000
    nr:
      insights:
        enabled: true
        date:
          format: MM/dd/yyyy hh:mm aa z
    security:
      basic:
        enabled: true
      user:
        name: ciusapi
        password: 'x3iY9P&*8%zK'
        role: APP_CLIENT
    application-service:
      host: ciapi-application-service
      port: 80
      url: /
      username: ciusapi
      password: 'x3iY9P&*8%zK'
      protocol: http
    ace-event-service:
      host: ciapi-aceapi-integration
      port: 80
      url: /
      username: aceapi
      password: aceapi123!
      protocol: http
    swagger:
      title: Business API for Admin Portal
      description: This API provides the services needed for Admin Portal to operate on Business Lines
      version: 1.0
      contact:
        name: West Unified Communications
        email: ciapi.support@west.com
      path:
        selector: /business/**
    server:
      port: ${PORT:8080}
      error:
        include-message: always
      servlet:
        encoding:
          force: true
    health:
      config:
        enabled: false
    logging:
      pattern:
        console: |
          %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{APP_NAME:-${newrelic.config.process_host.display_name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-},%X{SPACE_NAME:-${cloud.application.space_name:-}},%X{authuser},%X{_tid_}] 00 --- [%t] %logger : %replace(%msg){'[\r\n]',' -- '}--%replace(%ex){'[\r\n]',' -- '}%n
        level: |
          %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{APP_NAME:-${newrelic.config.process_host.display_name:-}},%X{X-B3-TraceId:-},%X{X-B3-SpanId:-},%X{X-Span-Export:-},%X{SPACE_NAME:-${cloud.application.space_name:-}},%X{authuser},%X{_tid_}] 00 --- [%t] %logger : %replace(%msg){'[\r\n]',' -- '}--%replace(%ex){'[\r\n]',' -- '}%n
      level:
        root: DEBUG
        org.springframework: DEBUG
        org.apache.http: ERROR
        org.hibernate: ERROR
        org.springframework.aop.interceptor.CustomizableTraceInterceptor: ERROR
        org.springframework.boot.autoconfigure: ERROR
        com.westuc.ciapi.Slf4jRequestLoggingFilter: ERROR
        org.springframework.boot.autoconfigure.security: ERROR
        org.springframework.security : ERROR
        org.springframework.jdbc: DEBUG
        org.springframework.amqp.rabbit.listener.BlockingQueueConsumer: ERROR
        com.netflix.eureka: DEBUG
        com.netflix.discovery: DEBUG
        com.rabbitmq.client: ERROR
        org.springframework.cloud.config.client: TRACE
        com.newrelic: INFO
    health.config.enabled: false
    spring.rabbitmq.ssl.validate-server-certificate: false
    #spring.rabbitmq.ssl.enabled: false
    #spring.rabbitmq.ssl.verify-hostname: false
    message: '****|CIAPI-BUSINESS-SERVICE|****'
    ---
    spring:
      datasource:
        url: 'jdbc:postgresql://cidmdb-rw-qa-den06.west.com:5432/cidmdb?currentSchema=ciapi_qa'
      config:
        activate:
          on-profile: den06-qa | gcp-den06-qa
    ---
    spring:
      datasource:
        url: 'jdbc:postgresql://cidmdb-rw-qa-swn01.west.com:5432/cidmdb?currentSchema=ciapi_qa'
      config:
        activate:
          on-profile: swn01-qa | gcp-swn01-qa
