apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: merope-backendconfig
spec:
  timeoutSec: 1800
  connectionDraining:
    drainingTimeoutSec: 1800
  healthCheck:
    checkIntervalSec: 15
    type: HTTP
    requestPath: /actuator/health
    port: 80