apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: merope-app-service
  creationTimestamp: null
  labels:
    app: merope-app-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "merope-backendconfig"}'
spec:
  ports:
    - name: merope-app-service
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: merope-app-service
  type: ClusterIP