---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: merope-backendconfig
spec:
  connectionDraining:
    drainingTimeoutSec: 1800
  healthCheck:
    checkIntervalSec: 15
    port: 80
    requestPath: /actuator/health
    type: HTTP
  timeoutSec: 1800
