apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: merope-app-service
  creationTimestamp: null
  labels:
    app: merope-app-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: merope-app-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: merope-app-service
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/merope/merope:FB-Devops-477-202202220552-d16a0fc
          name: merope-app-service
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-Dserver.port=80 -Dspring.application.name=merope-app-service"
            - name: SPRING_PROFILES_ACTIVE
              value: "qa"
            - name: SPRING_APPLICATION_NAME
              value: "merope-app-service"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: merope-app-service
              mountPath: /config
      volumes:
        - name: merope-app-service
          configMap:
            name: merope-service-qa
status: {}