---
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/backend-config: "{\"default\": \"merope-backendconfig\"}"
    cloud.google.com/neg: "{\"ingress\": true}"
  creationTimestamp: ~
  labels:
    app: merope-app-service
  name: merope-app-service
  namespace: default
spec:
  ports:
    -
      name: merope-app-service
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: merope-app-service
  type: ClusterIP
