apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ciapi-business-service
  creationTimestamp: null
  labels:
    app: ciapi-business-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ciapi-business-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ciapi-business-service
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/ciapi-business-service:NR-202201190552-99d660a
          imagePullPolicy: Always
          name: ciapi-business-service
          env:
              - name: JAVA_TOOL_OPTIONS
                value: "-Dserver.port=80 -Dspring.application.name=ciapi-business-service"
              - name: SPRING_PROFILES_ACTIVE
                value: "_APP_PROFILE"
              - name: SPRING_APPLICATION_NAME
                value: "ciapi-business-service"
              - name: GOOGLE_APPLICATION_CREDENTIALS
                value: /var/secrets/google/gkey.json
#          resources:
#            requests:
#              cpu: 200m
#              memory: 256Mi
#            limits:
#              cpu: 500m
#              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /message
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
#          # Configure the readiness probe
#          readinessProbe:
#            httpGet:
#              path: /message
#              port: 8080
          volumeMounts:
            - name: ciapi-business-service
              mountPath: /config
            - name: pub-sub-v
              mountPath: /var/secrets/google
      volumes:
        - name: ciapi-business-service
          configMap:
            name: ciapi-business-service-qa
        - name: pub-sub-v
          secret:
            secretName: iid-pub-sa-key
status: {}
