apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: ci-error-log-handler
  creationTimestamp: null
  labels:
    app: ci-error-log-handler
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "ci-error-log-handler"}'
spec:
  ports:
  - name: ci-error-log-handler
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ci-error-log-handler
  type: ClusterIP