apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ciapi-aceapi-integration
  creationTimestamp: null
  labels:
    app: ciapi-aceapi-integration
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ciapi-aceapi-integration
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 3
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ciapi-aceapi-integration
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/ciapi-aceapi-integration:NR-202201200626-0ae5a5d
          name: ciapi-aceapi-integration
          imagePullPolicy: Always
          env:
              - name: JAVA_TOOL_OPTIONS
                value: "-Dserver.port=80 -Dspring.application.name=ciapi-aceapi-integration"
              - name: SPRING_PROFILES_ACTIVE
                value: "${ENVIRONMENT}"
              - name: ENVIRONMENT
                valueFrom:
                  configMapKeyRef:
                    name: profile-config
                    key: ENVIRONMENT
              - name: SPRING_APPLICATION_NAME
                value: "ciapi-aceapi-integration"
#          resources:
#            requests:
#              cpu: 200m
#              memory: 256Mi
#            limits:
#              cpu: 500m
#              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /message
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
#          # Configure the readiness probe
#          readinessProbe:
#            httpGet:
#              path: /message
#              port: 8080
          volumeMounts:
            - name: ciapi-aceapi-integration
              mountPath: /config
      volumes:
        - name: ciapi-aceapi-integration
          configMap:
            name: ciapi-aceapi-integration-qa
status: {}
