apiVersion: v1
kind: Service
metadata:
  namespace: iid-qa
  name: ciapi-aceapi-integration
  creationTimestamp: null
  labels:
    app: ciapi-aceapi-integration
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "ciapi-aceapi-integration"}'
spec:
  ports:
  - name: ciapi-aceapi-integration
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ciapi-aceapi-integration
  type: ClusterIP