apiVersion: v1
kind: Service
metadata:
  namespace: ${name_space}
  name: ciapi-customer-service
  creationTimestamp: null
  labels:
    app: ciapi-customer-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "ciapi-customer-service"}'
spec:
  ports:
  - name: ciapi-customer-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ciapi-customer-service
  type: ClusterIP