apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ${name_space}
  name: ciapi-wso2is-jit-provisioning-service
  creationTimestamp: null
  labels:
    app: ciapi-wso2is-jit-provisioning-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ciapi-wso2is-jit-provisioning-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ciapi-wso2is-jit-provisioning-service
    spec:
      containers:
        - image: us-central1-docker.pkg.dev/cc-bo-portals-devtest-01/iid/ciapi-wso2is-jit-provisioning-service:latest
          name: ciapi-wso2is-jit-provisioning-service
          imagePullPolicy: Always
          env:
              - name: JAVA_TOOL_OPTIONS
                value: "-Dserver.port=80 -Dspring.application.name=ciapi-wso2is-jit-provisioning-service -Dnewrelic.config.log_file_name=STDOUT -Dnewrelic.config.license_key=d67210cdd7109fefbfdf3b9739f77e7d53acee76 -Dnewrelic.config.app_name=gcp-ciapi-wso2is-jit-provisioning-service -Dnewrelic.config.orgs=CommonIdentity -Dnewrelic.enable.java.8=true -Dnewrelic.home=/newrelic -javaagent:/newrelic/newrelic.jar -Dnewrelic.environment=test"
              - name: SPRING_PROFILES_ACTIVE
                value: "${app_profile}"
              - name: SPRING_APPLICATION_NAME
                value: "ciapi-wso2is-jit-provisioning-service"
          livenessProbe:
            httpGet:
              path: /message
              port: 80
            initialDelaySeconds: 80
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 4
            timeoutSeconds: 30
          volumeMounts:
            - name: ciapi-wso2is-jit-provisioning-service
              mountPath: /config
      volumes:
        - name: ciapi-wso2is-jit-provisioning-service
          configMap:
            name: ciapi-wso2is-jit-provisioning-service-qa

status: {}