apiVersion: v1
kind: Service
metadata:
  namespace: iid-qa
  name: ciapi-release-notes-service
  creationTimestamp: null
  labels:
    app: ciapi-release-notes-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
    cloud.google.com/backend-config: '{"default": "ciapi-release-notes-service"}'
spec:
  ports:
  - name: ciapi-release-notes-service
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ciapi-release-notes-service
  type: ClusterIP